# cd docker/add && ../docker.sh build
FROM rin/torch:cuda-10.1-cudnn7-devel-ubuntu18.04

# RUN conda install -y opencv yacs \
# RUN conda install -y scikit-image \
#  && conda clean -ya


RUN pip install fast_slic